
import { Quest } from './types';

export const QUESTS: Quest[] = [
  // 1-4: Python Basics
  {
    id: 'py-1',
    title: 'Variable Alchemy',
    category: 'Python Basics',
    difficulty: 'Beginner',
    description: 'Master the building blocks of Python: variables and data types.',
    objective: 'Create a script that stores personal data and performs a simple calculation.',
    startingCode: `# TODO: Define variables for name, age, and a boolean for status\n# Calculate birth year based on current_year = 2024`,
    solutionHint: 'Use age = 20 and current_year - age.',
    topics: ['Variables', 'Types', 'Arithmetic'],
    quiz: [{ question: 'What is the type of "3.14"?', options: ['int', 'float', 'string', 'bool'], correctAnswer: 1 }]
  },
  {
    id: 'py-2',
    title: 'Control Flow Maze',
    category: 'Python Basics',
    difficulty: 'Beginner',
    description: 'Learn to make decisions with if-statements.',
    objective: 'Build a simple login logic handler.',
    startingCode: `password = "secret123"\ninput_pw = "secret123"\n# TODO: Check if input_pw matches password`,
    solutionHint: 'Use == for comparison.',
    topics: ['Conditionals', 'Logic'],
  },
  {
    id: 'py-3',
    title: 'Looping Through Data',
    category: 'Python Basics',
    difficulty: 'Beginner',
    description: 'Automate repetitive tasks using for and while loops.',
    objective: 'Sum all numbers in a list using a loop.',
    startingCode: `nums = [10, 20, 30, 40, 50]\ntotal = 0\n# TODO: Iterate and sum`,
    solutionHint: 'Use "for num in nums:".',
    topics: ['Loops', 'Lists'],
  },
  {
    id: 'py-4',
    title: 'Function Factory',
    category: 'Python Basics',
    difficulty: 'Beginner',
    description: 'Encapsulate logic into reusable functions.',
    objective: 'Write a function that calculates the area of a circle.',
    startingCode: `import math\n\ndef get_area(radius):\n    # TODO: Implement formula\n    pass`,
    solutionHint: 'math.pi * radius**2',
    topics: ['Functions', 'Modules'],
  },
  // 5-8: Intermediate Python
  {
    id: 'py-5',
    title: 'List Comprehensions',
    category: 'Intermediate Python',
    difficulty: 'Intermediate',
    description: 'Write concise code with comprehensions.',
    objective: 'Filter a list of numbers to keep only even ones.',
    startingCode: `data = range(100)\n# TODO: Use list comprehension`,
    solutionHint: '[x for x in data if x % 2 == 0]',
    topics: ['Functional Programming'],
  },
  {
    id: 'py-6',
    title: 'OOP: The Hero Class',
    category: 'Intermediate Python',
    difficulty: 'Intermediate',
    description: 'Understand Classes and Objects.',
    objective: 'Create a Character class with health and attack methods.',
    startingCode: `class Character:\n    # TODO: Implement __init__ and attack`,
    solutionHint: 'Use "self" to refer to instance variables.',
    topics: ['OOP', 'Classes'],
  },
  {
    id: 'py-7',
    title: 'Exception Handling',
    category: 'Intermediate Python',
    difficulty: 'Intermediate',
    description: 'Learn to handle errors gracefully.',
    objective: 'Safe division function that avoids ZeroDivisionError.',
    startingCode: `def safe_div(a, b):\n    # TODO: try-except block`,
    solutionHint: 'try: ... except ZeroDivisionError: ...',
    topics: ['Exceptions', 'Debugging'],
  },
  {
    id: 'py-8',
    title: 'File I/O Secrets',
    category: 'Intermediate Python',
    difficulty: 'Intermediate',
    description: 'Reading and writing data to files.',
    objective: 'Read a CSV-style string and parse it.',
    startingCode: `csv_data = "name,score\\nAlice,95\\nBob,88"\n# TODO: Parse this into a list of dicts`,
    solutionHint: 'split("\\n") then split(",")',
    topics: ['IO', 'Parsing'],
  },
  // 9-12: Data Science
  {
    id: 'ds-1',
    title: 'NumPy Foundations',
    category: 'Data Science',
    difficulty: 'Intermediate',
    description: 'Master multi-dimensional arrays.',
    objective: 'Normalize a 2D array of pixel values.',
    startingCode: `import numpy as np\nimg = np.random.randint(0, 255, (28, 28))\n# TODO: Scale to 0-1 range`,
    solutionHint: 'Divide by 255.0',
    topics: ['NumPy', 'Arrays'],
  },
  {
    id: 'ds-2',
    title: 'Pandas Wrangling',
    category: 'Data Science',
    difficulty: 'Intermediate',
    description: 'DataFrames and manipulation.',
    objective: 'Find the average score for each department.',
    startingCode: `import pandas as pd\ndf = pd.DataFrame({"dept": ["A", "B", "A"], "score": [90, 80, 70]})\n# TODO: Group by and mean`,
    solutionHint: 'df.groupby("dept").mean()',
    topics: ['Pandas', 'Aggregation'],
  },
  {
    id: 'ds-3',
    title: 'Matplotlib Visuals',
    category: 'Data Science',
    difficulty: 'Intermediate',
    description: 'Plotting trends and distributions.',
    objective: 'Plot a sine wave.',
    startingCode: `import matplotlib.pyplot as plt\nimport numpy as np\nx = np.linspace(0, 10, 100)\n# TODO: Plot x vs sin(x)`,
    solutionHint: 'plt.plot(x, np.sin(x))',
    topics: ['Visualization'],
  },
  {
    id: 'ds-4',
    title: 'The Cleaning Lab',
    category: 'Data Science',
    difficulty: 'Advanced',
    description: 'Real-world data cleaning pipeline.',
    objective: 'Impute missing values and remove outliers.',
    startingCode: `import pandas as pd\n# TODO: Handle NaNs in df`,
    solutionHint: 'df.fillna() or df.dropna()',
    topics: ['Preprocessing'],
  },
  // 13-16: ML & AI
  {
    id: 'ml-1',
    title: 'Linear Regression',
    category: 'Machine Learning',
    difficulty: 'Advanced',
    description: 'Predict numerical values.',
    objective: 'Train a basic regressor on housing data.',
    startingCode: `from sklearn.linear_model import LinearRegression\n# TODO: Fit and Predict`,
    solutionHint: 'model.fit(X, y)',
    topics: ['Scikit-learn', 'Regression'],
  },
  {
    id: 'ml-2',
    title: 'Clustering Chaos',
    category: 'Machine Learning',
    difficulty: 'Advanced',
    description: 'Find patterns in unlabeled data.',
    objective: 'Implement K-Means clustering.',
    startingCode: `from sklearn.cluster import KMeans\n# TODO: Cluster the data points`,
    solutionHint: 'n_clusters=3',
    topics: ['Unsupervised'],
  },
  {
    id: 'ml-3',
    title: 'Neural Network Spark',
    category: 'Advanced AI',
    difficulty: 'Advanced',
    description: 'The start of Deep Learning.',
    objective: 'Create a Perceptron to solve XOR.',
    startingCode: `import numpy as np\n# TODO: Simple MLP logic`,
    solutionHint: 'Use weights and a step function.',
    topics: ['Deep Learning', 'Neural Networks'],
  },
  {
    id: 'ml-4',
    title: 'The Final Frontier',
    category: 'Advanced AI',
    difficulty: 'Advanced',
    description: 'Deploying your first pipeline.',
    objective: 'Build an end-to-end MLOps pipeline.',
    startingCode: `from sklearn.pipeline import Pipeline\n# TODO: Bundle Scaler and Model`,
    solutionHint: 'Pipeline([("scaler", StandardScaler()), ("clf", SVC())])',
    topics: ['MLOps', 'Pipelines'],
  }
];
